# Generated by Django 4.2.7 on 2023-12-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="hashed_token",
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
